publish_mode: editorial_workflow
media_folder: "/content/images"
site_url: https://aeroteameindhoven.nl/
logo_url: https://aeroteameindhoven.nl/icons/icon-512x512.png

# Development (https://decapcms.org/docs/working-with-a-local-git-repository/)
local_backend: true
backend:
  name: git-gateway

# # Production
# backend:
#   name: github
#   repo: aeroteameindhoven/website
#   branch: main
#   use_graphql: true
#   squash_merges: true
#   base_url: https://actively-working-fawn.edgecompute.app/

collections:
  - name: "sponsors"
    label: "Sponsors"
    label_singular: Sponsor
    folder: "/content/sponsors/markdown"
    media_folder: "/content/sponsors/images"
    public_folder: ""
    preview_path: "/partners/"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    identifier_field: "name"
    extension: "md"
    summary: "[{{package | upper}}] {{name}}"
    view_groups:
      - label: Package
        field: package
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Logo", name: "logo", widget: "image", choose_url: false, allow_multiple: false }
      - { label: "URL", name: "url", widget: "string" }
      - { label: "Package", name: "package", widget: "select", options: ["platinum", "gold", "silver"] }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "projects"
    label: "Projects"
    folder: "/content/projects/markdown"
    media_folder: "/content/projects/images"
    public_folder: "/"
    preview_path: "/projects/"
    create: true
    slug: "{{slug}}"
    identifier_field: "name"
    view_groups:
      - label: Years
        field: academic_year
    editor:
      preview: false
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - {
          label: "Images",
          name: images,
          widget: "list",
          summary: "{{fields.image}}",
          field: { label: "Image", name: "image", widget: "image", choose_url: false, allow_multiple: false }
        }
      - {
          label: "3D Model",
          name: model,
          widget: file,
          required: false,
          allow_multiple: false,
          choose_url: false,
          media_folder: "/content/projects/models",
          public_folder: "/"
        }
      - { label: "Academic Year", name: "academic_year", widget: "number", value_type: "int" }
      - { label: "Blurb", name: "blurb", widget: "text" }
      - { label: "Extended Description", name: "body", widget: "markdown" }

  - name: teams
    label: Teams
    label_singular: Team
    folder: /content/teams/json
    create: true

    media_folder: "/content/teams/images/{{slug}}"
    public_folder: ""

    preview_path: "/team/{{slug}}"

    identifier_field: "year"
    format: json

    summary: "{{slug}}: {{description}}"

    fields:
      - label: Academic Year
        name: year
        widget: string
        hint: "The academic years in the form XX-XX"
        pattern: ["[0-9]{2}-[0-9]{2}", "must match the form XX-XX"]
      - { label: Short Description, name: description, widget: string }
      - label: Members
        name: members
        widget: list
        label_singular: Member
        summary: "{{first_name}} {{last_name}}"
        fields:
          # - { label: Hidden, name: hidden, widget: boolean, default: false }
          - { label: First Name, name: first_name, widget: string }
          - { label: Last Name, name: last_name, widget: string }
          - { label: Study, name: study, widget: string, required: false }
          - { label: Study Level, name: study_level, widget: string, required: false }
          - { label: LinkedIn, name: linkedin, widget: string, required: false, hint: "LinkedIn username" }
          - { label: Function, name: function, widget: string, required: false }
          - { label: Subteams, name: subteams, widget: list }
          - label: Aero Email
            name: email
            widget: string
            pattern: [".*@aeroteameindhoven.nl$", "must end in @aeroteameindhoven.nl"]
          - label: Photo
            name: photo
            widget: image
            required: false
            choose_url: false
            allow_multiple: false
