publish_mode: editorial_workflow
media_folder: "/content/images"

# Development (https://decapcms.org/docs/working-with-a-local-git-repository/)
local_backend: true
backend:
  name: git-gateway

# # Production
# backend:
#   name: github
#   repo: aeroteameindhoven/website
#   branch: main
#   use_graphql: true
#   squash_merges: true
#   base_url: https://actively-working-fawn.edgecompute.app/

collections:
  - name: "sponsors"
    label: "Sponsors"
    folder: "/content/sponsors/markdown"
    media_folder: "/content/sponsors/images"
    public_folder: "/"
    preview_path: "/partners/"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    identifier_field: "name"
    extension: "md"
    summary: "[{{package | upper}}] {{name}}"
    view_groups:
      - label: Packages
        field: package
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Logo", name: "logo", widget: "image", choose_url: false, allow_multiple: false }
      - { label: "URL", name: "url", widget: "string" }
      - { label: "Package", name: "package", widget: "select", options: ["platinum", "gold", "silver"] }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "projects"
    label: "Projects"
    folder: "/content/projects/markdown"
    media_folder: "/content/projects/images"
    public_folder: "/"
    preview_path: "/projects/"
    create: true
    slug: "{{slug}}"
    identifier_field: "name"
    view_groups:
      - label: Years
        field: academic_year
    editor:
      preview: false
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - {
          label: "Images",
          name: images,
          widget: "list",
          summary: "{{fields.image}}",
          field: { label: "Image", name: "image", widget: "image", choose_url: false, allow_multiple: false }
        }
      - {
          label: "3D Model",
          name: model,
          widget: file,
          required: false,
          allow_multiple: false,
          choose_url: false,
          media_folder: "/content/projects/models",
          public_folder: "/"
        }
      - { label: "Academic Year", name: "academic_year", widget: "number", value_type: "int" }
      - { label: "Blurb", name: "blurb", widget: "text" }
      - { label: "Extended Description", name: "body", widget: "markdown" }
